CREATE OR REPLACE VIEW ADMIN_SUBJECT_VIEW
AS
SELECT CO.C_NAME"과정명"
     , R.R_NAME"강의실"
     , SU.SJ_NAME"과목명"
     , OS.START_DATE"과목시작일"
     , OS.END_DATE"과목종료일"
     , BO.B_NAME"교재명"
     , PR.P_NAME"교수자명"
FROM TBL_COURSE CO, TBL_ROOM R, TBL_SUBJECT SU, TBL_OP_SUBJECT OS, TBL_BOOK BO, TBL_PROFESSOR PR, TBL_OP_COURSE OC
WHERE CO.C_CODE(+) = OC.C_CODE
  AND R.R_CODE(+) = OC.R_CODE 
  AND OC.OPC_CODE = OS.OPC_CODE(+)
  AND SU.SJ_CODE(+) = OS.SJ_CODE 
  AND BO.B_CODE(+) = OS.B_CODE 
  AND PR.P_CODE(+) = OS.P_CODE;
--==>> View ADMIN_SUBJECT_VIEW이(가) 생성되었습니다.
