SELECT *
FROM TBL_SUGANG;

CREATE OR REPLACE PROCEDURE PRC_SUGANG_UPDATE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
, V_S_CODE    IN TBL_SUGANG.S_CODE%TYPE
, V_OPC_CODE  IN TBL_SUGANG.OPC_CODE%TYPE
, V_SG_DATE   IN TBL_SUGANG.SG_DATE%TYPE
)
IS  
    --EXCEPTION에 사용될 변수와 값
    RESULTCODE_SG_CODE               NUMBER(1);
    RESULTCODE_S_CODE               NUMBER(1);
    RESULTCODE_OPC_CODE             NUMBER(1);
    
    USER_DEFINE_ERROR_SG_CODE EXCEPTION;
    USER_DEFINE_ERROR_S_CODE EXCEPTION;
    USER_DEFINE_ERROR_OPC_CODE EXCEPTION; 
    
BEGIN
    SELECT COUNT(*) INTO RESULTCODE_SG_CODE 
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;   
    
    IF RESULTCODE_SG_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_SG_CODE;
    END IF;

    SELECT COUNT(*) INTO RESULTCODE_S_CODE 
    FROM TBL_STUDENT
    WHERE S_CODE = V_S_CODE;   
    
    IF RESULTCODE_S_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_S_CODE;
    END IF;

    SELECT COUNT(*) INTO RESULTCODE_OPC_CODE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;   
    
    IF RESULTCODE_OPC_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_OPC_CODE;
    END IF;     
    
    
    -- UPDATE 쿼리문
    UPDATE TBL_SUGANG
    SET S_CODE = V_SG_CODE, OPC_CODE = V_OPC_CODE, SG_DATE = V_SG_DATE
    WHERE SG_CODE = V_SG_CODE;

    -- EXCEPTION
    EXCEPTION 
    WHEN USER_DEFINE_ERROR_SG_CODE
        THEN RAISE_APPLICATION_ERROR(-20012, '수강코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_S_CODE
        THEN RAISE_APPLICATION_ERROR(-20009, '학생코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_OPC_CODE
        THEN RAISE_APPLICATION_ERROR(-20010, '개설과정코드가 존재하지 않습니다.');
            ROLLBACK;          
    WHEN OTHERS
        THEN  ROLLBACK;
        
    -- 커밋
    COMMIT;
END;
--==>> Procedure PRC_SUGANG_UPDATE이(가) 컴파일되었습니다.



CREATE OR REPLACE PROCEDURE PRC_SUGANG_DELETE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
)
IS
    --EXCEPTION에 사용될 변수와 값
    RESULTCODE_SG_CODE               NUMBER(1);
    
    USER_DEFINE_ERROR_SG_CODE EXCEPTION;
    
BEGIN
    SELECT COUNT(*) INTO RESULTCODE_SG_CODE 
    FROM TBL_SUGANG
    WHERE SG_CODE=V_SG_CODE;

    IF RESULTCODE_SG_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_SG_CODE;
    END IF; 
    
    -- DELETE 쿼리문
    DELETE 
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;
    
    -- EXCEPTION
    EXCEPTION 
    WHEN USER_DEFINE_ERROR_SG_CODE
        THEN RAISE_APPLICATION_ERROR(-20012, '수강코드가 존재하지 않습니다.');
                 ROLLBACK;          
    WHEN OTHERS
        THEN    ROLLBACK;
        
END;
--==>> Procedure PRC_SUGANG_DELETE이(가) 컴파일되었습니다.



