--○ PRC_SUGANG_UPDATE 
SELECT *
FROM TBL_SUGANG;

CREATE OR REPLACE PROCEDURE PRC_SUGANG_UPDATE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
, V_S_CODE    IN TBL_SUGANG.S_CODE%TYPE
, V_OPC_CODE  IN TBL_SUGANG.OPC_CODE%TYPE
, V_SG_DATE   IN TBL_SUGANG.SG_DATE%TYPE
)
IS  
BEGIN
    -- UPDATE 쿼리문
    UPDATE TBL_SUGANG
    SET S_CODE = V_SG_CODE, OPC_CODE = V_OPC_CODE, SG_DATE = V_SG_DATE
    WHERE SG_CODE = V_SG_CODE;
    
    -- 커밋
    COMMIT;
END;
--==>> Procedure PRC_SUGANG_UPDATE이(가) 컴파일되었습니다.


--○ PRC_SUGANG_DELETE
CREATE OR REPLACE PROCEDURE PRC_SUGANG_DELETE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
)
IS
BEGIN
    -- DELETE 쿼리문
    DELETE 
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;
END;
--==>> Procedure PRC_SUGANG_DELETE이(가) 컴파일되었습니다.






