SELECT USER
FROM DUAL;
--==>> PMJ


-- ■■■ TBL_ADMIN 관리자 테이블 생성 ■■■ --

CREATE TABLE TBL_ADMIN
( A_CODE        VARCHAR2(6)
, A_NAME        VARCHAR2(10)    CONSTRAINT ADMIN_A_NAME_NN NOT NULL
, A_ID          VARCHAR2(11)    CONSTRAINT ADMIN_A_ID_NN NOT NULL
, A_PW          VARCHAR2(20)    CONSTRAINT ADMIN_A_PW_NN NOT NULL
, A_REG_DATE    DATE            DEFAULT SYSDATE
, CONSTRAINT ADMIN_A_CODE_PK PRIMARY KEY(A_CODE)
, CONSTRAINT ADMIN_A_ID_UK UNIQUE(A_ID)
);
--==>> Table TBL_ADMIN이(가) 생성되었습니다.

/*
INSERT INTO TBL_ADMIN(A_CODE, A_NAME, A_ID, A_PW)
VALUES('A00001', '관리자1', 'admin1', 'admin1234');
INSERT INTO TBL_ADMIN(A_CODE, A_NAME, A_ID, A_PW)
VALUES('A00002', '관리자2', 'admin2', 'admin5678');
*/


-- ■■■ TBL_STUDENT 학생 테이블 생성 ■■■ --

CREATE TABLE TBL_STUDENT
( S_CODE        VARCHAR2(6)
, S_NAME        VARCHAR2(10)    CONSTRAINT STUDENT_S_NAME_NN NOT NULL
, S_SSN         CHAR(14)        CONSTRAINT STUDENT_S_SSN_NN NOT NULL
, S_ID          VARCHAR2(11)    CONSTRAINT STUDENT_S_ID_NN NOT NULL
, S_PW          VARCHAR2(20)    CONSTRAINT STUDENT_S_PW_NN NOT NULL
, S_REG_DATE    DATE            DEFAULT SYSDATE
, CONSTRAINT STUDENT_S_CODE_PK PRIMARY KEY(S_CODE)
, CONSTRAINT STUDENT_S_ID_UK UNIQUE(S_ID)
, CONSTRAINT STUDENT_S_SSN_UK UNIQUE(S_SSN)
);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.

/*
INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
VALUES('S00001', '박민지', '960907-2012345', '01039315569', '2012345');
INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
VALUES('S00002', '심혜진', '940708-2012346', '01071019504', '2012346');
INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
VALUES('S00003', '이하림', '971022-2012347', '01040331022', '2012347');
INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
VALUES('S00004', '이희주', '950107-2012348', '01082695439', '2012348');
INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
VALUES('S00005', '전혜림', '950630-2012349', '01080019506', '2012349');
*/

-- ■■■ TBL_PROFESSOR 교수 테이블 생성 ■■■ --

CREATE TABLE TBL_PROFESSOR
( P_CODE        VARCHAR2(6)
, P_NAME        VARCHAR2(10)    CONSTRAINT PROFESSOR_P_NAME_NN NOT NULL
, P_SSN         CHAR(14)        CONSTRAINT PROFESSOR_P_SSN_NN NOT NULL
, P_ID          VARCHAR2(11)    CONSTRAINT PROFESSOR_P_ID_NN NOT NULL
, P_PW          VARCHAR2(20)    CONSTRAINT PROFESSOR_P_PW_NN NOT NULL
, P_REG_DATE    DATE            DEFAULT SYSDATE
, CONSTRAINT PROFESSOR_P_CODE_PK PRIMARY KEY(P_CODE)
, CONSTRAINT PROFESSOR_P_ID_UK UNIQUE(P_ID)
, CONSTRAINT PROFESSOR_P_SSN_UK UNIQUE(P_SSN)
);
--==>> Table TBL_PROFESSOR이(가) 생성되었습니다.
/*
INSERT INTO TBL_PROFESSOR(P_CODE, P_NAME, P_SSN, P_ID, P_PW)
VALUES('P00001', '김호진', '-1123456', '01048484114', '1123456');
*/


-- ■■■ TBL_BOOK 교재 테이블 생성 ■■■ --

CREATE TABLE TBL_BOOK 
( B_CODE     VARCHAR2(4)        
, B_NAME     VARCHAR2(60)       CONSTRAINT BOOK_B_NAME_NN NOT NULL 
, CONSTRAINT BOOK_B_CODE_PK PRIMARY KEY(B_CODE)
, CONSTRAINT BOOK_B_NAME_UK UNIQUE(B_NAME)
);
--==>> Table TBL_BOOK이(가) 생성되었습니다.

-- ■■■ TBL_SUBJECT 과목 테이블 생성 ■■■ --

CREATE TABLE TBL_SUBJECT 
( SJ_CODE    VARCHAR2(4)
, SJ_NAME    VARCHAR2(60)        CONSTRAINT SUBJECT_NAME_NN NOT NULL
, CONSTRAINT SUBJECT_CODE_PK PRIMARY KEY(SJ_CODE)
, CONSTRAINT SUBJECT_NAME_UK UNIQUE(SJ_NAME)
);
--==>> Table TBL_SUBJECT이(가) 생성되었습니다.


-- ■■■ TBL_COURSE 과정 테이블 생성 ■■■ --

CREATE TABLE TBL_COURSE
( C_CODE         VARCHAR2(4)
, C_NAME         VARCHAR2(60)   CONSTRAINT COURSE_NAME_NN NOT NULL
, CONSTRAINT COURSE_CODE_PK PRIMARY KEY(C_CODE)
, CONSTRAINT COURSE_NAME_UK UNIQUE(C_NAME)
);
--==>> Table TBL_COURSE이(가) 생성되었습니다.


-- ■■■ TBL_ROOM 강의실 테이블 생성 ■■■ --

CREATE TABLE TBL_ROOM
( R_CODE    VARCHAR2(4)
, R_NAME    VARCHAR2(30)    CONSTRAINT ROOM_R_NAME_NN NOT NULL
, R_EXPLAIN   VARCHAR2(60)
, CONSTRAINT ROOM_R_CODE_PK PRIMARY KEY(R_CODE)
, CONSTRAINT ROOM_R_NAME_UK UNIQUE(R_NAME)
);
--==>> Table TBL_ROOM이(가) 생성되었습니다.

/*
INSERT INTO TBL_ROOM(R_CODE, R_NAME, EXPLAIN)
VALUES('R001', 'A강의실', '2층');
INSERT INTO TBL_ROOM(R_CODE, R_NAME, C_CODE, EXPLAIN)
VALUES('R002', 'B강의실', '2층');
INSERT INTO TBL_ROOM(R_CODE, R_NAME, C_CODE, EXPLAIN)
VALUES('R003', 'F강의실', '4층');
*/



-- ■■■ TBL_ALLOT 배점 테이블 생성 ■■■ --

CREATE TABLE TBL_ALLOT
(AL_CODE NUMBER(4) 
,A_ALLOT NUMBER(3) CONSTRAINT ALLOT_A_ALLOT_NN NOT NULL 
,W_ALLOT NUMBER(3) CONSTRAINT ALLOT_W_ALLOT_NN NOT NULL 
,P_ALLOT NUMBER(3) CONSTRAINT ALLOT_P_ALLOT_NN NOT NULL 
,CONSTRAINT ALLOT_AL_CODE_PK PRIMARY KEY(AL_CODE)
);
--==>> Table TBL_ALLOT이(가) 생성되었습니다.


CREATE SEQUENCE SEQ_ALLOT
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_ALLOT이(가) 생성되었습니다.



-- ■■■ TBL_OP_COURSE 과정개설 테이블 생성 ■■■ --

CREATE TABLE TBL_OP_COURSE
(OPC_CODE       NUMBER(4)
,C_CODE         VARCHAR2(4) CONSTRAINT OP_COURSE_C_CODE_NN NOT NULL
,R_CODE         VARCHAR2(4) CONSTRAINT OP_COURSE_R_CODE_NN NOT NULL
,START_DATE     DATE
,END_DATE       DATE
,CONSTRAINT OP_COURSE_OPC_CODE_PK PRIMARY KEY(OPC_CODE)
,CONSTRAINT OP_COURSE_C_CODE_FK FOREIGN KEY(C_CODE)
            REFERENCES TBL_COURSE(C_CODE)
,CONSTRAINT OP_COURSE_R_CODE_FK FOREIGN KEY(R_CODE)
            REFERENCES TBL_ROOM(R_CODE)
,CONSTRAINT OP_COURSE_DATE_CK CHECK(START_DATE < END_DATE)
);
--==>> Table TBL_OP_COURSE이(가) 생성되었습니다.

CREATE SEQUENCE SEQ_OP_COURSE
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_OP_COURSE이(가) 생성되었습니다.


-- ■■■ TBL_OP_SUBJECT 과목개설 테이블 생성 ■■■ --

CREATE TABLE TBL_OP_SUBJECT
(OPS_CODE NUMBER(4)     
,SJ_CODE  VARCHAR2(4)   CONSTRAINT OP_SUBJECT_SJ_CODE_NN NOT NULL  
,OPC_CODE NUMBER(4)     CONSTRAINT OP_SUBJECT_OPC_CODE_NN NOT NULL
,P_CODE VARCHAR2(6)     CONSTRAINT OP_SUBJECT_P_CODE_NN NOT NULL
,B_CODE VARCHAR2(4)     CONSTRAINT OP_SUBJECT_B_CODE_NN NOT NULL
,AL_CODE NUMBER(4)      CONSTRAINT OP_SUBJECT_AL_CODE_NN NOT NULL
,START_DATE DATE        CONSTRAINT OP_SUBJECT_START_DATE_NN NOT NULL
,END_DATE DATE          CONSTRAINT OP_SUBJECT_END_DATE_NN NOT NULL 
, CONSTRAINT OP_SUBJECT_OPS_CODE_PK PRIMARY KEY(OPS_CODE)
, CONSTRAINT  OP_SUBJECT_SJ_CODE_FK FOREIGN KEY(SJ_CODE)
                        REFERENCES TBL_SUBJECT(SJ_CODE)
, CONSTRAINT  OP_SUBJECT_OPC_CODE_FK FOREIGN KEY(OPC_CODE)
                        REFERENCES TBL_OP_COURSE(OPC_CODE)
, CONSTRAINT  OP_SUBJECT_P_CODE_FK FOREIGN KEY(P_CODE)
                        REFERENCES TBL_PROFESSOR(P_CODE)
, CONSTRAINT  OP_SUBJECT_B_CODE_FK FOREIGN KEY(B_CODE)
                        REFERENCES TBL_BOOK(B_CODE)
, CONSTRAINT  OP_SUBJECT_AL_CODE_FK FOREIGN KEY(AL_CODE)
                        REFERENCES TBL_ALLOT(AL_CODE)
, CONSTRAINT OP_SUBJECT_END_DATE_CK CHECK(START_DATE<END_DATE)
);
--==>> Table TBL_OP_SUBJECT이(가) 생성되었습니다.

CREATE SEQUENCE SEQ_OPS_CODE
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_OPS_CODE이(가) 생성되었습니다.


CREATE SEQUENCE SEQ_OP_SUBJECT
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_OP_SUBJECT이(가) 생성되었습니다.


-- ■■■ TBL_SUGANG 수강신청 테이블 생성 ■■■ --


CREATE TABLE TBL_SUGANG
( SG_CODE    NUMBER(4)    
, S_CODE     VARCHAR2(6)  CONSTRAINT SUGANG_S_CODE_NN NOT NULL
, OPC_CODE   NUMBER(4)    CONSTRAINT SUGANG_OPC_CODE_NN NOT NULL
, SG_DATE    DATE         DEFAULT SYSDATE
, CONSTRAINT SUGANG_SG_CODE_PK PRIMARY KEY(SG_CODE) 
, CONSTRAINT SUGANG_S_CODE_FK FOREIGN KEY(S_CODE)
             REFERENCES TBL_STUDENT(S_CODE)            
, CONSTRAINT SUGANG_OPC_CODE_FK FOREIGN KEY(OPC_CODE)
             REFERENCES TBL_OP_COURSE(OPC_CODE)                            
);
--==>> Table TBL_SUGANG이(가) 생성되었습니다.

CREATE SEQUENCE SEQ_SUGANG
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_SUGANG이(가) 생성되었습니다.


-- ■■■ TBL_DROP 중도탈락 테이블 생성 ■■■ --

CREATE TABLE TBL_DROP
( D_CODE    NUMBER(4)
, SG_CODE   NUMBER(4)   CONSTRAINT DROP_SG_CODE_NN NOT NULL 
, REASON    VARCHAR2(60)
, DR_DATE   DATE        DEFAULT SYSDATE
, CONSTRAINT DROP_D_CODE_PK PRIMARY KEY(D_CODE)
, CONSTRAINT DROP_SG_CODE_FK FOREIGN KEY(SG_CODE)
             REFERENCES TBL_SUGANG(SG_CODE)
);
--==>> Table TBL_DROP이(가) 생성되었습니다.

CREATE SEQUENCE SEQ_DROP
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_DROP이(가) 생성되었습니다.

-- ■■■ TBL_SCORE 성적 테이블 생성 ■■■ --

CREATE TABLE TBL_SCORE
( SC_CODE   NUMBER(4)
, SG_CODE   NUMBER(4)   CONSTRAINT SCORE_SG_CODE_NN NOT NULL
, OPS_CODE  NUMBER(4)   CONSTRAINT SCORE_OPS_CODE_NN NOT NULL
, A_SCORE   NUMBER(3)
, W_SCORE   NUMBER(3)
, P_SCORE   NUMBER(3)
, CONSTRAINT SCORE_SC_CODE_PK PRIMARY KEY(SC_CODE)
, CONSTRAINT SCORE_SG_CODE_FK FOREIGN KEY(SG_CODE)
             REFERENCES TBL_SUGANG(SG_CODE)
, CONSTRAINT SCORE_OPS_CODE_FK FOREIGN KEY(OPS_CODE)
             REFERENCES TBL_OP_SUBJECT(OPS_CODE)
);
--==>> Table TBL_SCORE이(가) 생성되었습니다.

CREATE SEQUENCE SEQ_SCORE
START WITH 1001
INCREMENT BY 1
MINVALUE 1001
MAXVALUE 9999
NOCACHE;
--==>> Sequence SEQ_SCORE이(가) 생성되었습니다.

DROP SEQUENCE SEQ_SCORE;






------------------------- 테이블 구조 확인 -------------------------------------


DESC TBL_ADMIN;
/*
이름         널?       유형           
---------- -------- ------------ 
A_CODE     NOT NULL VARCHAR2(6)  
A_NAME     NOT NULL VARCHAR2(10) 
A_ID       NOT NULL VARCHAR2(11) 
A_PW       NOT NULL VARCHAR2(20) 
A_REG_DATE          DATE         
*/

DESC TBL_STUDENT;
/*
이름         널?       유형           
---------- -------- ------------ 
S_CODE     NOT NULL VARCHAR2(6)  
S_NAME     NOT NULL VARCHAR2(10) 
S_SSN      NOT NULL CHAR(14)     
S_ID       NOT NULL VARCHAR2(11) 
S_PW       NOT NULL VARCHAR2(20) 
S_REG_DATE          DATE       
*/

DESC TBL_PROFESSOR;
/*
이름         널?       유형           
---------- -------- ------------ 
P_CODE     NOT NULL VARCHAR2(6)  
P_NAME     NOT NULL VARCHAR2(10) 
P_SSN      NOT NULL CHAR(14)     
P_ID       NOT NULL VARCHAR2(11) 
P_PW       NOT NULL VARCHAR2(20) 
P_REG_DATE          DATE  
*/

DESC TBL_BOOK;
/*
이름     널?       유형           
------ -------- ------------ 
B_CODE NOT NULL VARCHAR2(4)  
B_NAME NOT NULL VARCHAR2(60)
*/

DESC TBL_SUBJECT;
/*
이름      널?       유형           
------- -------- ------------ 
SJ_CODE NOT NULL VARCHAR2(4)  
SJ_NAME NOT NULL VARCHAR2(60)
*/

DESC TBL_COURSE;
/*
이름     널?       유형           
------ -------- ------------ 
C_CODE NOT NULL VARCHAR2(4)  
C_NAME NOT NULL VARCHAR2(60)
*/

DESC TBL_ROOM;
/*
이름      널?       유형           
------- -------- ------------ 
R_CODE  NOT NULL VARCHAR2(4)  
R_NAME  NOT NULL VARCHAR2(30) 
R_EXPLAIN        VARCHAR2(60)
*/

DESC TBL_ALLOT;
/*
이름      널?       유형        
------- -------- --------- 
AL_CODE NOT NULL NUMBER(4) 
A_ALLOT NOT NULL NUMBER(3) 
W_ALLOT NOT NULL NUMBER(3) 
P_ALLOT NOT NULL NUMBER(3) 
*/

DESC TBL_OP_COURSE;
/*
이름         널?       유형          
---------- -------- ----------- 
OPC_CODE   NOT NULL NUMBER(4)   
C_CODE     NOT NULL VARCHAR2(4) 
R_CODE     NOT NULL VARCHAR2(4) 
START_DATE NOT NULL DATE        
END_DATE   NOT NULL DATE        
*/

DESC TBL_OP_SUBJECT;
/*
이름         널?       유형          
---------- -------- ----------- 
OPS_CODE   NOT NULL NUMBER(4)   
SJ_CODE    NOT NULL VARCHAR2(4) 
OPC_CODE   NOT NULL NUMBER(4)   
P_CODE     NOT NULL VARCHAR2(6) 
B_CODE     NOT NULL VARCHAR2(4) 
AL_CODE    NOT NULL NUMBER(4)   
START_DATE NOT NULL DATE        
END_DATE   NOT NULL DATE 
*/

DESC TBL_SUGANG;
/*
이름       널?       유형          
-------- -------- ----------- 
SG_CODE  NOT NULL NUMBER(4)   
S_CODE   NOT NULL VARCHAR2(6) 
OPC_CODE NOT NULL NUMBER(4)   
SG_DATE           DATE        
*/

DESC TBL_DROP;
/*
이름      널?       유형           
------- -------- ------------ 
D_CODE  NOT NULL NUMBER(4)    
SG_CODE NOT NULL NUMBER(4)    
REASON           VARCHAR2(60) 
DR_DATE          DATE         
*/

DESC TBL_SCORE;
/*
이름       널?       유형        
-------- -------- --------- 
SC_CODE  NOT NULL NUMBER(4) 
SG_CODE  NOT NULL NUMBER(4) 
OPS_CODE NOT NULL NUMBER(4) 
A_SCORE           NUMBER(3) 
W_SCORE           NUMBER(3) 
P_SCORE           NUMBER(3)
*/


------------------------제약조건 확인-------------------------------------------

--※ 제약조건 확인 전용 뷰(VIEW) 생성
CREATE OR REPLACE VIEW VIEW_SG_CONSTCHECK
AS
SELECT UC.OWNER "OWNER"
     , UC.CONSTRAINT_NAME "CONSTRAINT_NAME"
     , UC.TABLE_NAME "TABLE_NAME"
     , UC.CONSTRAINT_TYPE "CONSTRAINT_TYPE"
     , UCC.COLUMN_NAME "COLUMN_NAME"
     , UC.SEARCH_CONDITION "SEARCH_CONDITION"
     , UC.DELETE_RULE "DELETE_RULE"
FROM USER_CONSTRAINTS UC JOIN USER_CONS_COLUMNS UCC
ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME;
--==>> View VIEW_SG_CONSTCHECK이(가) 생성되었습니다.

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_ADMIN';
--==>>
/*
HR	ADMIN_A_NAME_NN	TBL_ADMIN	C	A_NAME	"A_NAME" IS NOT NULL	
HR	ADMIN_A_ID_NN	TBL_ADMIN	C	A_ID	"A_ID" IS NOT NULL	
HR	ADMIN_A_PW_NN	TBL_ADMIN	C	A_PW	"A_PW" IS NOT NULL	
HR	ADMIN_A_CODE_PK	TBL_ADMIN	P	A_CODE		
HR	ADMIN_A_ID_UK	TBL_ADMIN	U	A_ID		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_STUDENT';
--==>>
/*
HR	STUDENT_S_NAME_NN	TBL_STUDENT	C	S_NAME	"S_NAME" IS NOT NULL	
HR	STUDENT_S_SSN_NN	TBL_STUDENT	C	S_SSN	"S_SSN" IS NOT NULL	
HR	STUDENT_S_ID_NN	    TBL_STUDENT C	S_ID	"S_ID" IS NOT NULL	
HR	STUDENT_S_PW_NN 	TBL_STUDENT C	S_PW	"S_PW" IS NOT NULL	
HR	STUDENT_S_CODE_PK	TBL_STUDENT	P	S_CODE		
HR	STUDENT_S_ID_UK	    TBL_STUDENT U	S_ID		
HR	STUDENT_S_SSN_UK	TBL_STUDENT	U	S_SSN		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_PROFESSOR';
--==>>
/*
HR	PROFESSOR_P_NAME_NN	TBL_PROFESSOR	C	P_NAME	"P_NAME" IS NOT NULL	
HR	PROFESSOR_P_SSN_NN	TBL_PROFESSOR	C	P_SSN	"P_SSN" IS NOT NULL	
HR	PROFESSOR_P_ID_NN	TBL_PROFESSOR	C	P_ID	"P_ID" IS NOT NULL	
HR	PROFESSOR_P_PW_NN	TBL_PROFESSOR	C	P_PW	"P_PW" IS NOT NULL	
HR	PROFESSOR_P_CODE_PK	TBL_PROFESSOR	P	P_CODE		
HR	PROFESSOR_P_ID_UK	TBL_PROFESSOR	U	P_ID		
HR	PROFESSOR_P_SSN_UK	TBL_PROFESSOR	U	P_SSN		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_BOOK';
--==>>
/*
HR	BOOK_B_NAME_NN	TBL_BOOK	C	B_NAME	"B_NAME" IS NOT NULL	
HR	BOOK_B_CODE_PK	TBL_BOOK	P	B_CODE		
HR	BOOK_B_NAME_UK	TBL_BOOK	U	B_NAME		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_SUBJECT';
--==>>
/*
HR	SUBJECT_NAME_NN	TBL_SUBJECT	C	SJ_NAME	"SJ_NAME" IS NOT NULL	
HR	SUBJECT_CODE_PK	TBL_SUBJECT	P	SJ_CODE		
HR	SUBJECT_NAME_UK	TBL_SUBJECT	U	SJ_NAME		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_COURSE';
--==>>
/*
HR	COURSE_NAME_NN	TBL_COURSE	C	C_NAME	"C_NAME" IS NOT NULL	
HR	COURSE_CODE_PK	TBL_COURSE	P	C_CODE		
HR	COURSE_NAME_UK	TBL_COURSE	U	C_NAME		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_ROOM';
--==>>
/*
HR	ROOM_R_NAME_NN	TBL_ROOM	C	R_NAME	"R_NAME" IS NOT NULL	
HR	ROOM_R_CODE_PK	TBL_ROOM	P	R_CODE		
HR	ROOM_R_NAME_UK	TBL_ROOM	U	R_NAME		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_ALLOT';
--==>>
/*
HR	ALLOT_A_ALLOT_NN	TBL_ALLOT	C	A_ALLOT	"A_ALLOT" IS NOT NULL	
HR	ALLOT_W_ALLOT_NN	TBL_ALLOT	C	W_ALLOT	"W_ALLOT" IS NOT NULL	
HR	ALLOT_P_ALLOT_NN	TBL_ALLOT	C	P_ALLOT	"P_ALLOT" IS NOT NULL	
HR	ALLOT_AL_CODE_PK	TBL_ALLOT	P	AL_CODE		
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_OP_COURSE';
--==>>
/*
HR	OP_COURSE_C_CODE_NN	TBL_OP_COURSE	C	C_CODE	"C_CODE" IS NOT NULL	
HR	OP_COURSE_R_CODE_NN	TBL_OP_COURSE	C	R_CODE	"R_CODE" IS NOT NULL	
HR	OP_COURSE_DATE_CK	TBL_OP_COURSE	C	START_DATE	START_DATE < END_DATE	
HR	OP_COURSE_DATE_CK	TBL_OP_COURSE	C	END_DATE	START_DATE < END_DATE	
HR	OP_COURSE_OPC_CODE_PKTBL_OP_COURSE	P	OPC_CODE		
HR	OP_COURSE_C_CODE_FK	TBL_OP_COURSE	R	C_CODE		NO ACTION
HR	OP_COURSE_R_CODE_FK	TBL_OP_COURSE	R	R_CODE		NO ACTION
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_OP_SUBJECT';
--==>>
/*
HR	OP_SUBJECT_SJ_CODE_NN	TBL_OP_SUBJECT	C	SJ_CODE	"SJ_CODE" IS NOT NULL	
HR	OP_SUBJECT_OPC_CODE_NN	TBL_OP_SUBJECT	C	OPC_CODE	"OPC_CODE" IS NOT NULL	
HR	OP_SUBJECT_P_CODE_NN	TBL_OP_SUBJECT	C	P_CODE	"P_CODE" IS NOT NULL	
HR	OP_SUBJECT_B_CODE_NN	TBL_OP_SUBJECT	C	B_CODE	"B_CODE" IS NOT NULL	
HR	OP_SUBJECT_AL_CODE_NN	TBL_OP_SUBJECT	C	AL_CODE	"AL_CODE" IS NOT NULL	
HR	OP_SUBJECT_START_DATE_NNTBL_OP_SUBJECT	C	START_DATE	"START_DATE" IS NOT NULL	
HR	OP_SUBJECT_END_DATE_NN	TBL_OP_SUBJECT	C	END_DATE	"END_DATE" IS NOT NULL	
HR	OP_SUBJECT_END_DATE_CK	TBL_OP_SUBJECT	C	START_DATE	START_DATE<END_DATE	
HR	OP_SUBJECT_END_DATE_CK	TBL_OP_SUBJECT	C	END_DATE	START_DATE<END_DATE	
HR	OP_SUBJECT_OPS_CODE_PK	TBL_OP_SUBJECT	P	OPS_CODE		
HR	OP_SUBJECT_SJ_CODE_FK	TBL_OP_SUBJECT	R	SJ_CODE		NO ACTION
HR	OP_SUBJECT_OPC_CODE_FK	TBL_OP_SUBJECT	R	OPC_CODE		NO ACTION
HR	OP_SUBJECT_P_CODE_FK	TBL_OP_SUBJECT	R	P_CODE		NO ACTION
HR	OP_SUBJECT_B_CODE_FK	TBL_OP_SUBJECT	R	B_CODE		NO ACTION
HR	OP_SUBJECT_AL_CODE_FK	TBL_OP_SUBJECT	R	AL_CODE		NO ACTION
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_SUGANG';
--==>>
/*
HR	SUGANG_S_CODE_NN	TBL_SUGANG	C	S_CODE	    "S_CODE" IS NOT NULL	
HR	SUGANG_OPC_CODE_NN	TBL_SUGANG	C	OPC_CODE	"OPC_CODE" IS NOT NULL	
HR	SUGANG_SG_CODE_PK	TBL_SUGANG	P	SG_CODE		
HR	SUGANG_S_CODE_FK	TBL_SUGANG	R	S_CODE		NO ACTION
HR	SUGANG_OPC_CODE_FK	TBL_SUGANG	R	OPC_CODE	NO ACTION
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_DROP';
--==>>
/*
HR	DROP_SG_CODE_NN	TBL_DROP	C	SG_CODE	"SG_CODE" IS NOT NULL	
HR	DROP_D_CODE_PK	TBL_DROP	P	D_CODE		
HR	DROP_SG_CODE_FK	TBL_DROP	R	SG_CODE		NO ACTION
*/

SELECT *
FROM VIEW_SG_CONSTCHECK
WHERE TABLE_NAME = 'TBL_SCORE';
--==>>
/*
HR	SCORE_SG_CODE_NN	TBL_SCORE	C	SG_CODE	    "SG_CODE" IS NOT NULL	
HR	SCORE_OPS_CODE_NN	TBL_SCORE	C	OPS_CODE	"OPS_CODE" IS NOT NULL	
HR	SCORE_SC_CODE_PK	TBL_SCORE	P	SC_CODE		
HR	SCORE_SG_CODE_FK	TBL_SCORE	R	SG_CODE		NO ACTION
HR	SCORE_OPS_CODE_FK	TBL_SCORE	R	OPS_CODE	NO ACTION
*/



--------------------- 시퀀스 확인 ----------------------------------------------

SELECT *
FROM USER_SEQUENCES;
--==>>
/*
SEQ_ALLOT   	1001	9999	1	N	N	0	1001
SEQ_DROP	    1001	9999	1	N	N	0	1001
SEQ_OPS_CODE	1001	9999	1	N	N	0	1001
SEQ_OP_COURSE	1001	9999	1	N	N	0	1001
SEQ_SCORE	    1001	9999	1	N	N	0	1001
SEQ_SUGANG	    1001	9999	1	N	N	0	1001
*/


---------------------------


DROP SEQUENCE SEQ_ALLOT;
DROP SEQUENCE SEQ_DROP;
DROP SEQUENCE SEQ_OPS_CODE;
DROP SEQUENCE SEQ_OP_COURSE;
DROP SEQUENCE SEQ_SCORE;
DROP SEQUENCE SEQ_SUGANG;


DROP TABLE TBL_SCORE;

DROP TABLE TBL_DROP;

DROP TABLE TBL_SUGANG;

DROP TABLE TBL_OP_SUBJECT;

DROP TABLE TBL_OP_COURSE;

DROP TABLE TBL_SUBJECT;

DROP TABLE TBL_COURSE;

DROP TABLE TBL_ROOM;

DROP TABLE TBL_STUDENT;

DROP TABLE TBL_ALLOT;

DROP TABLE TBL_ADMIN;

DROP TABLE TBL_PROFESSOR;

DROP TABLE TBL_ROOM;



--------------------------- 프로시저 모음 --------------------------------------

--○ 학생 등록/수정/삭제 + 학생 조회
-- PRC_STUDENT_INSERT → 입력 정보는 학생 이름, 주민 뒷자리는 학생 로그인시 패스워드로 사용되도록)
-- PRC_STUDNET_UPDATE
-- PRC_STUDENT_DELETE 
-- ADMIN_STUDENT_VIEW

-- 학생 등록
CREATE OR REPLACE PROCEDURE PRC_STUDENT_INSERT
( V_NAME    IN TBL_STUDENT.S_NAME%TYPE
, V_SSN     IN TBL_STUDENT.S_SSN%TYPE
, V_ID      IN TBL_STUDENT.S_ID%TYPE
)
IS
    V_CODE  TBL_STUDENT.S_CODE%TYPE;
    V_PW    TBL_STUDENT.S_PW%TYPE;
    
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    -- V_CODE 자동입력
    SELECT CONCAT('S', NVL(MAX(TO_NUMBER(SUBSTR(S_CODE, 2, 5))), 10000) + 1) INTO V_CODE
    FROM TBL_STUDENT;
    
    -- V_PW
    V_PW := SUBSTR(V_SSN, 8);
    
    -- 예외 발생(SSN 잘못 입력시)
    IF(V_SSN NOT LIKE '______-_______')
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- INSERT 쿼리문
    INSERT INTO TBL_STUDENT(S_CODE, S_NAME, S_SSN, S_ID, S_PW)
    VALUES (V_CODE, V_NAME, V_SSN, V_ID, V_PW);
    
    -- 커밋 
    COMMIT;
    
    -- 예외 처리
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20003, '주민번호를 하이픈(-) 포함 14자리로 입력해주세요');    
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
END;
--==>> Procedure PRC_STUDENT_INSERT이(가) 컴파일되었습니다.


-- 학생 수정
CREATE OR REPLACE PROCEDURE PRC_STUDENT_UPDATE
( V_CODE        IN TBL_STUDENT.S_CODE%TYPE
, V_NAME        IN TBL_STUDENT.S_NAME%TYPE
, V_SSN         IN TBL_STUDENT.S_SSN%TYPE
, V_ID          IN TBL_STUDENT.S_ID%TYPE
, V_PW          IN TBL_STUDENT.S_PW%TYPE
, V_REG_DATE    IN TBL_STUDENT.S_REG_DATE%TYPE
)
IS  
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    -- 예외 발생(SSN 잘못 입력시)
    IF(V_SSN NOT LIKE '______-_______')
        THEN RAISE USER_DEFINE_ERROR;
    END IF;

    -- UPDATE 쿼리문
    UPDATE TBL_STUDENT
    SET S_NAME = V_NAME
      , S_SSN = V_SSN
      , S_ID = V_ID
      , S_PW = V_PW
      , S_REG_DATE = V_REG_DATE
    WHERE S_CODE = V_CODE;
    
    -- 커밋
    COMMIT;
    
    -- 예외 처리
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20003, '주민번호를 하이픈(-) 포함 14자리로 입력해주세요.');     --> 주민번호가 잘못된 형식이라고 세부적으로 알려줘야 하지 않을까?
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;

END;
--==>> Procedure PRC_STUDENT_UPDATE이(가) 컴파일되었습니다.


-- 학생 삭제
CREATE OR REPLACE PROCEDURE PRC_STUDENT_DELETE
( V_CODE    IN TBL_STUDENT.S_CODE%TYPE
)
IS
BEGIN
    -- DELETE 쿼리문 작성 
    DELETE
    FROM TBL_STUDENT
    WHERE S_CODE = V_CODE;
    
    -- 커밋 
    COMMIT; 
END;
--==>> Procedure PRC_STUDENT_DELETE이(가) 컴파일되었습니다.





--○ 교수 등록/수정/삭제

-- 교수 등록
CREATE OR REPLACE PROCEDURE PRC_PROFESSOR_INSERT
(V_NAME     IN TBL_PROFESSOR.P_NAME%TYPE
,V_SSN      IN TBL_PROFESSOR.P_SSN%TYPE
,V_ID       IN TBL_PROFESSOR.P_ID%TYPE
)
IS  
    V_CODE  TBL_PROFESSOR.P_CODE%TYPE;
    V_PW    TBL_PROFESSOR.P_PW%TYPE;
    
    USER_DEFINE_ERROR       EXCEPTION;
BEGIN
    SELECT CONCAT('P',NVL(MAX(TO_NUMBER(SUBSTR(P_CODE,2,5))),10000)+1) INTO V_CODE
    FROM TBL_PROFESSOR;
    
    V_PW := SUBSTR(V_SSN,8);
    
    IF(V_SSN NOT LIKE '______-_______')
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    
    INSERT INTO TBL_PROFESSOR(P_CODE, P_NAME,P_SSN,P_ID,P_PW)
    VALUES (V_CODE,V_NAME,V_SSN,V_ID,V_PW);
    
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20001, '입력 정보가 잘못 되었습니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
END;
--==>>Procedure PRC_PROFESSOR_INSERT이(가) 컴파일되었습니다.


-- 교수 수정
CREATE OR REPLACE PROCEDURE PRC_PROFESSOR_UPDATE 
(V_CODE         IN TBL_PROFESSOR.P_CODE%TYPE
,V_NAME         IN TBL_PROFESSOR.P_NAME%TYPE
,V_SSN          IN TBL_PROFESSOR.P_SSN%TYPE
,V_ID           IN TBL_PROFESSOR.P_ID%TYPE
,V_PW           IN TBL_PROFESSOR.P_PW%TYPE
,V_REG_DATE     IN TBL_PROFESSOR.P_REG_DATE%TYPE
)
IS
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    IF(V_SSN NOT LIKE '______-_______')
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    UPDATE TBL_PROFESSOR
    SET P_NAME = V_NAME
       ,P_SSN = V_SSN
       ,P_ID = V_ID
       ,P_PW = V_PW
       ,P_REG_DATE = V_REG_DATE
    WHERE P_CODE = V_CODE;
    
    EXCEPTION 
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20001, '입력 정보가 잘못 되었습니다.');
        WHEN OTHERS 
            THEN ROLLBACK;
END;
--==>>Procedure PRC_PROFESSOR_UPDATE이(가) 컴파일되었습니다.


-- 교수 삭제
CREATE OR REPLACE PROCEDURE PRC_PROFESSOR_DELETE
( V_CODE    IN TBL_PROFESSOR.P_CODE%TYPE
)
IS
BEGIN
   
    DELETE
    FROM TBL_PROFESSOR
    WHERE P_CODE = V_CODE;
    
   
    COMMIT; 
END;
--==>>Procedure PRC_PROFESSOR_DELETE이(가) 컴파일되었습니다.





--○ 과정 등록 / 수정 / 삭제 (TBL_OP_COURSE) 프로시저 생성

-- 개설 과정 등록
CREATE OR REPLACE PROCEDURE PRC_OP_COURSE_INSERT
( V_C_NAME        IN TBL_COURSE.C_NAME%TYPE               
, V_R_CODE        IN TBL_ROOM.R_CODE%TYPE                 
, V_START_DATE    IN TBL_OP_COURSE.START_DATE%TYPE         
, V_END_DATE      IN TBL_OP_COURSE.END_DATE%TYPE
)
IS
    -- 과정명을 과정코드로 입력하기 위한 변수 선언
    V_C_CODE    TBL_COURSE.C_CODE%TYPE;
    
    -- 예외 처리 시 확인할 변수
    V_RC_NAME   TBL_COURSE.C_NAME%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 예외 확인: 입력받은 C_NAME(과정명)이 정확한지 확인
    SELECT COUNT(*) INTO V_RC_NAME
    FROM TBL_COURSE
    WHERE C_NAME = V_C_NAME;
    
    IF (V_RC_NAME != 1)
     THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- C_NAME(과정명)을 입력하면 비교하여 C_CODE(과정코드) 값 얻어오기
    SELECT C_CODE INTO V_C_CODE
    FROM TBL_COURSE
    WHERE C_NAME = V_C_NAME;
    
    -- TBL_OP_COURSE 테이블에 데이터 입력 (과정 개설)
    INSERT INTO TBL_OP_COURSE(OPC_CODE, C_CODE, R_CODE, START_DATE, END_DATE)
    VALUES(SEQ_OP_COURSE.NEXTVAL, V_C_CODE, V_R_CODE, V_START_DATE, V_END_DATE);
    
    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20004, '과정명을 잘못 입력하셨습니다.');
                   ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
END;
--==>> Procedure PRC_OP_COURSE_INSERT이(가) 컴파일되었습니다.


-- 개설 과정 수정
CREATE OR REPLACE PROCEDURE PRC_OP_COURSE_UPDATE
( V_OPC_CODE      IN TBL_OP_COURSE.OPC_CODE%TYPE
, V_C_NAME        IN TBL_COURSE.C_NAME%TYPE
, V_R_CODE        IN TBL_ROOM.R_CODE%TYPE
, V_START_DATE    IN TBL_OP_COURSE.START_DATE%TYPE 
, V_END_DATE      IN TBL_OP_COURSE.END_DATE%TYPE
)
IS
    -- 과정명을 과정코드로 입력하기 위한 변수 선언
    V_C_CODE      TBL_COURSE.C_CODE%TYPE;
    
    -- 예외 처리 시 확인할 변수
    V_ROPC_CODE   TBL_COURSE.C_CODE%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 예외 확인: 입력받은 OPC_CODE(개설과정코드)가 정확한지 확인
    SELECT COUNT(*) INTO V_ROPC_CODE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;
    
    IF (V_ROPC_CODE = 0)
     THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- C_NAME(과정명)을 입력하면 비교하여 C_CODE(과정코드) 값 얻어오기
    SELECT C_CODE INTO V_C_CODE
    FROM TBL_COURSE
    WHERE C_NAME = V_C_NAME;
    
    -- TBL_OP_COURSE 테이블 데이터 수정
    UPDATE TBL_OP_COURSE
    SET C_CODE = V_C_CODE, R_CODE = V_R_CODE, START_DATE = V_START_DATE, END_DATE = V_END_DATE
    WHERE OPC_CODE = V_OPC_CODE; 
    
    -- 커밋
    COMMIT;

    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20005, '과정코드를 잘못 입력하셨습니다.');
                   ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
END;
--==>> Procedure PRC_OP_COURSE_UPDATE이(가) 컴파일되었습니다.


-- 개설 과정 삭제
CREATE OR REPLACE PROCEDURE PRC_OP_COURSE_DELETE
(  V_OPC_CODE      IN TBL_OP_COURSE.OPC_CODE%TYPE
)
IS
    -- 예외 처리 시 확인할 변수
    V_ROPC_CODE   TBL_COURSE.C_CODE%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 예외 확인: 입력받은 OPC_CODE(개설과정코드)가 정확한지 확인
    SELECT COUNT(*) INTO V_ROPC_CODE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;
    
    IF (V_ROPC_CODE = 0)
     THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- TBL_OP_COURSE 테이블 데이터 삭제
    DELETE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;
    
    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20005, '과정코드를 잘못 입력하셨습니다.');
                   ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
END;
--==>> Procedure PRC_OP_COURSE_DELETE이(가) 컴파일되었습니다.





--○ 개설 과목 등록/수정/삭제

-- 개설과목 등록
CREATE OR REPLACE PROCEDURE PRC_OP_SUBJECT_INSERT
( V_SJ_CODE           IN TBL_SUBJECT.SJ_CODE%TYPE
, V_OPC_CODE          IN TBL_OP_COURSE.OPC_CODE%TYPE
, V_P_CODE            IN TBL_PROFESSOR.P_CODE%TYPE
, V_B_CODE            IN TBL_BOOK.B_CODE%TYPE
, V_AL_CODE           IN TBL_ALLOT.AL_CODE%TYPE
, V_START_DATE        IN TBL_OP_SUBJECT.START_DATE%TYPE
, V_END_DATE          IN TBL_OP_SUBJECT.END_DATE%TYPE

)
IS
    OPC_STARTDATE       TBL_OP_COURSE.START_DATE%TYPE;
    OPC_ENDDATE         TBL_OP_COURSE.END_DATE%TYPE;

    V_S_DATE    TBL_OP_SUBJECT.START_DATE%TYPE;
    V_E_DATE    TBL_OP_SUBJECT.END_DATE%TYPE;
    
    CURSOR CUR_OPS_DATE
    IS
    SELECT START_DATE, END_DATE
    FROM TBL_OP_SUBJECT
    WHERE OPC_CODE = V_OPC_CODE;
    
    USER_DEFINE_ERROR    EXCEPTION;
    USER_DEFINE_ERROR2   EXCEPTION; 
    USER_DEFINE_ERROR3   EXCEPTION;
    
BEGIN
    -- 과정기간안에 날짜가 포함되지 않을 시 예외 발생
    SELECT START_DATE, END_DATE INTO OPC_STARTDATE, OPC_ENDDATE       
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;
    
    IF (V_START_DATE < OPC_STARTDATE OR V_END_DATE > OPC_ENDDATE)
        THEN RAISE USER_DEFINE_ERROR2;
    END IF;
    
    -- 같은 과정의 다른 과목들과 날짜가 겹칠 시 예외 발생
    OPEN CUR_OPS_DATE;
    
    LOOP
        FETCH CUR_OPS_DATE INTO V_S_DATE, V_E_DATE;
        
        EXIT WHEN CUR_OPS_DATE%NOTFOUND;
        
        IF((V_START_DATE BETWEEN V_S_DATE AND V_E_DATE) OR (V_END_DATE BETWEEN V_S_DATE AND V_E_DATE))
            THEN RAISE USER_DEFINE_ERROR;
        END IF;
        
    END LOOP;
    
    CLOSE CUR_OPS_DATE;
    
    -- INSERT 쿼리문 
    INSERT INTO TBL_OP_SUBJECT(OPS_CODE, SJ_CODE, OPC_CODE, P_CODE, B_CODE, AL_CODE, START_DATE, END_DATE)
    VALUES (SEQ_OPS_CODE.NEXTVAL, V_SJ_CODE, V_OPC_CODE, V_P_CODE, V_B_CODE,V_AL_CODE,V_START_DATE, V_END_DATE);
    
    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
            
            WHEN USER_DEFINE_ERROR
                THEN RAISE_APPLICATION_ERROR(-20010,'입력한 날짜가 기존 과목 날짜와 겹칩니다. 다시 시도하세요.');    -- RAISE_APPLICATION_ERROR(-에러번호,'구문' )는 함수!
                     ROLLBACK;
            WHEN USER_DEFINE_ERROR2   
                THEN RAISE_APPLICATION_ERROR(-20011,'입력한 날짜가 기존 개설강좌 날짜 안에 유효하지 않습니다.');
                     ROLLBACK;
            WHEN OTHERS   --- IF ELSIF ELSE 구문에서 ELSE 느낌~ 
                THEN DBMS_OUTPUT.PUT_LINE('예외처리 되지 않은 에러가 발생했습니다.');
                     ROLLBACK;
END;


-- 개설 과목 수정 
CREATE OR REPLACE PROCEDURE PRC_OP_SUBJECT_UPDATE
( V_OPS_CODE          IN TBL_OP_SUBJECT.OPS_CODE%TYPE  
, V_SJ_CODE           IN TBL_SUBJECT.SJ_CODE%TYPE
, V_OPC_CODE          IN TBL_OP_COURSE.OPC_CODE%TYPE
, V_P_CODE            IN TBL_PROFESSOR.P_CODE%TYPE
, V_B_CODE            IN TBL_BOOK.B_CODE%TYPE
, V_AL_CODE           IN TBL_ALLOT.AL_CODE%TYPE
, V_START_DATE        IN TBL_OP_SUBJECT.START_DATE%TYPE
, V_END_DATE          IN TBL_OP_SUBJECT.END_DATE%TYPE
)
IS

    -- 예외 처리 시 확인할 변수
    V_ROPS_CODE   TBL_SUBJECT.SJ_CODE%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 예외 확인: 입력받은 OPS_CODE(개설과목코드)가 정확한지 확인
    SELECT COUNT(*) INTO V_ROPS_CODE
    FROM TBL_OP_SUBJECT
    WHERE OPS_CODE = V_OPS_CODE;
    
    IF (V_ROPS_CODE = 0)
     THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- TBL_OP_COURSE 테이블 데이터 수정
    UPDATE TBL_OP_SUBJECT
    SET SJ_CODE = V_SJ_CODE, OPC_CODE = V_OPC_CODE, P_CODE=V_P_CODE, B_CODE=V_B_CODE
      , AL_CODE=V_AL_CODE,START_DATE = V_START_DATE, END_DATE = V_END_DATE
    WHERE OPS_CODE = V_OPS_CODE; 
    
    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20017, '과목코드를 잘못 입력하셨습니다.');
                   ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
    
END; 
--==>> Procedure PRC_OP_SUBJECT_UPDATE이(가) 컴파일되었습니다.


-- 개설 과목 삭제
CREATE OR REPLACE PROCEDURE PRC_OP_SUBJECT_DELETE
(  V_OPS_CODE      IN TBL_OP_SUBJECT.OPS_CODE%TYPE
)
IS
    -- 예외 처리 시 확인할 변수
    V_ROPS_CODE   TBL_SUBJECT.SJ_CODE%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 예외 확인: 입력받은 OPS_CODE(개설과정코드)가 정확한지 확인
    SELECT COUNT(*) INTO V_ROPS_CODE
    FROM TBL_OP_SUBJECT
    WHERE OPS_CODE = V_OPS_CODE;
    
    IF (V_ROPS_CODE = 0)
     THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- TBL_OP_SUBJECT 테이블 데이터 삭제
    DELETE
    FROM TBL_OP_SUBJECT
    WHERE OPS_CODE = V_OPS_CODE;
    
    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20017, '과목코드를 잘못 입력하셨습니다.');
                   ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
END;
--==>> Procedure PRC_OP_SUBJECT_DELETE이(가) 컴파일되었습니다.



 
--○ 배점 등록
CREATE OR REPLACE PROCEDURE PRC_ALLOT_INSERT
( V_A_ALLOT          IN TBL_ALLOT.A_ALLOT%TYPE             -- 출결
, V_W_ALLOT          IN TBL_ALLOT.W_ALLOT%TYPE             -- 필기
, V_P_ALLOT          IN TBL_ALLOT.P_ALLOT%TYPE             -- 실기
)
IS      
    V_AL_CODE       TBL_ALLOT.AL_CODE%TYPE;   
    -- 사용자 정의 예외처리 변수 선언
    USER_DEFINE_ERROR EXCEPTION;  
    
BEGIN 
    -- 각 배점의 총합이 100이 아니면 에러 발생
    IF(V_A_ALLOT + V_W_ALLOT + V_P_ALLOT != 100)
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
        
    -- 각각의 배점 입력 시 'AL'로 시작하는 시퀀스 배점 코드 생성하며 데이터 입력됨
    INSERT INTO TBL_ALLOT(AL_CODE, A_ALLOT, W_ALLOT, P_ALLOT)
    VALUES(SEQ_ALLOT.NEXTVAL, V_A_ALLOT, V_W_ALLOT, V_P_ALLOT);
    
    COMMIT;
    
    -- 에러 발생 시 아래 메시지 출력 후 롤백됨
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20006, '배점은 100점 만점을 기준으로 입력해주세요.');
                 ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;    
END;
--==>> Procedure PRC_ALLOT_INSERT이(가) 컴파일되었습니다.





--○ 수강 입력/수정/등록

--수강 테이블 입력
CREATE OR REPLACE PROCEDURE PRC_SUGANG_INSERT
( V_S_CODE      IN TBL_STUDENT.S_CODE%TYPE
, V_OPC_CODE    IN TBL_OP_COURSE.OPC_CODE%TYPE
)
IS
    --EXCEPTION에 사용될 변수와 값
    RESULTCODE_S_CODE               NUMBER(1);
    RESULTCODE_OVERLAP              NUMBER(1);
    RESULTCODE_OPC_CODE             NUMBER(1);
    
    USER_DEFINE_ERROR_S_CODE EXCEPTION;
    USER_DEFINE_ERROR_OVERLAP EXCEPTION;
    USER_DEFINE_ERROR_OPC_CODE EXCEPTION; 
    
BEGIN
    SELECT COUNT(*) INTO RESULTCODE_S_CODE 
    FROM TBL_STUDENT 
    WHERE S_CODE = V_S_CODE;   
    
    IF RESULTCODE_S_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_S_CODE;
    END IF;

    SELECT COUNT(*) INTO RESULTCODE_OVERLAP
    FROM TBL_SUGANG 
    WHERE S_CODE = V_S_CODE;   
    
    IF RESULTCODE_OVERLAP = 1
        THEN  RAISE USER_DEFINE_ERROR_OVERLAP;
    END IF;
    
    SELECT COUNT(*) INTO RESULTCODE_OPC_CODE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;   
    
    IF RESULTCODE_OPC_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_OPC_CODE;
    END IF;     
    
    -- INSERT 쿼리문
    INSERT INTO TBL_SUGANG(SG_CODE, S_CODE, OPC_CODE, SG_DATE)
    VALUES (SEQ_SUGANG.NEXTVAL, V_S_CODE, V_OPC_CODE, SYSDATE);
    
    
    EXCEPTION 
    WHEN USER_DEFINE_ERROR_S_CODE
        THEN RAISE_APPLICATION_ERROR(-20009, '학생코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_OPC_CODE
        THEN RAISE_APPLICATION_ERROR(-20010, '개설과정코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_OVERLAP
        THEN RAISE_APPLICATION_ERROR(-20011, '이미 과정을 등록한 학생입니다.');
            ROLLBACK;            
    WHEN OTHERS
        THEN  ROLLBACK;
            
    -- 커밋 
    COMMIT;
END;
--==>> Procedure PRC_SUGANG_INSERT이(가) 컴파일되었습니다.

-- 수강 신청 수정
CREATE OR REPLACE PROCEDURE PRC_SUGANG_UPDATE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
, V_S_CODE    IN TBL_SUGANG.S_CODE%TYPE
, V_OPC_CODE  IN TBL_SUGANG.OPC_CODE%TYPE
, V_SG_DATE   IN TBL_SUGANG.SG_DATE%TYPE
)
IS  
    --EXCEPTION에 사용될 변수와 값
    RESULTCODE_SG_CODE               NUMBER(1);
    RESULTCODE_S_CODE               NUMBER(1);
    RESULTCODE_OPC_CODE             NUMBER(1);
    
    USER_DEFINE_ERROR_SG_CODE EXCEPTION;
    USER_DEFINE_ERROR_S_CODE EXCEPTION;
    USER_DEFINE_ERROR_OPC_CODE EXCEPTION; 
    
BEGIN
    SELECT COUNT(*) INTO RESULTCODE_SG_CODE 
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;   
    
    IF RESULTCODE_SG_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_SG_CODE;
    END IF;

    SELECT COUNT(*) INTO RESULTCODE_S_CODE 
    FROM TBL_STUDENT
    WHERE S_CODE = V_S_CODE;   
    
    IF RESULTCODE_S_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_S_CODE;
    END IF;

    SELECT COUNT(*) INTO RESULTCODE_OPC_CODE
    FROM TBL_OP_COURSE
    WHERE OPC_CODE = V_OPC_CODE;   
    
    IF RESULTCODE_OPC_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_OPC_CODE;
    END IF;     
    
    
    -- UPDATE 쿼리문
    UPDATE TBL_SUGANG
    SET S_CODE = V_SG_CODE, OPC_CODE = V_OPC_CODE, SG_DATE = V_SG_DATE
    WHERE SG_CODE = V_SG_CODE;

    -- EXCEPTION
    EXCEPTION 
    WHEN USER_DEFINE_ERROR_SG_CODE
        THEN RAISE_APPLICATION_ERROR(-20012, '수강코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_S_CODE
        THEN RAISE_APPLICATION_ERROR(-20009, '학생코드가 존재하지 않습니다.');
            ROLLBACK;
    WHEN USER_DEFINE_ERROR_OPC_CODE
        THEN RAISE_APPLICATION_ERROR(-20010, '개설과정코드가 존재하지 않습니다.');
            ROLLBACK;          
    WHEN OTHERS
        THEN  ROLLBACK;
        
    -- 커밋
    COMMIT;
END;
--==>> Procedure PRC_SUGANG_UPDATE이(가) 컴파일되었습니다.


-- 수강 신청 삭제
CREATE OR REPLACE PROCEDURE PRC_SUGANG_DELETE
( V_SG_CODE   IN TBL_SUGANG.SG_CODE%TYPE
)
IS
    --EXCEPTION에 사용될 변수와 값
    RESULTCODE_SG_CODE               NUMBER(1);
    
    USER_DEFINE_ERROR_SG_CODE EXCEPTION;
    
BEGIN
    SELECT COUNT(*) INTO RESULTCODE_SG_CODE 
    FROM TBL_SUGANG
    WHERE SG_CODE=V_SG_CODE;

    IF RESULTCODE_SG_CODE = 0
        THEN  RAISE USER_DEFINE_ERROR_SG_CODE;
    END IF; 
    
    -- DELETE 쿼리문
    DELETE 
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;
    
    -- EXCEPTION
    EXCEPTION 
    WHEN USER_DEFINE_ERROR_SG_CODE
        THEN RAISE_APPLICATION_ERROR(-20012, '수강코드가 존재하지 않습니다.');
                 ROLLBACK;          
    WHEN OTHERS
        THEN    ROLLBACK;
        
END;
--==>> Procedure PRC_SUGANG_DELETE이(가) 컴파일되었습니다.


--○ 성적 입력/수정/삭제

-- 성적 입력
CREATE OR REPLACE PROCEDURE PRC_SCORE_INSERT
( V_SG_CODE             IN TBL_SUGANG.SG_CODE%TYPE
, V_OPS_CODE            IN TBL_OP_SUBJECT.OPS_CODE%TYPE
, V_A_SCORE             IN TBL_SCORE.A_SCORE%TYPE
, V_W_SCORE             IN TBL_SCORE.W_SCORE%TYPE
, V_P_SCORE             IN TBL_SCORE.P_SCORE%TYPE
)
IS
BEGIN
    -- 데이터 입력
    INSERT INTO TBL_SCORE(SC_CODE, SG_CODE, OPS_CODE, A_SCORE, W_SCORE, P_SCORE)
    VALUES(SEQ_SCORE.NEXTVAL, V_SG_CODE, V_OPS_CODE, V_A_SCORE, V_W_SCORE, V_P_SCORE);

    -- 커밋
    COMMIT;
END;
--==>> Procedure PRC_SCORE_INSERT이(가) 컴파일되었습니다.

--예외처리 (미완)
CREATE OR REPLACE PROCEDURE PRC_SCORE_INSERT
( V_SG_CODE             IN TBL_SUGANG.SG_CODE%TYPE
, V_OPS_CODE            IN TBL_OP_SUBJECT.OPS_CODE%TYPE
, V_A_SCORE             IN TBL_SCORE.A_SCORE%TYPE
, V_W_SCORE             IN TBL_SCORE.W_SCORE%TYPE
, V_P_SCORE             IN TBL_SCORE.P_SCORE%TYPE
)
IS
    V_A_ALLOT            TBL_ALLOT.A_ALLOT%TYPE;
    V_W_ALLOT            TBL_ALLOT.W_ALLOT%TYPE;
    V_P_ALLOT            TBL_ALLOT.P_ALLOT%TYPE;

    V_OPC_CODE           TBL_OP_COURSE.OPC_CODE%TYPE;
    --CV_OPC_CODE          TBL_OP_COURSE.OPC_CODE%TYPE;
    V_AL_CODE            TBL_ALLOT.AL_CODE%TYPE;
    
    -- 사용자 정의 예외에 대한 변수 선언
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    
    -- 개설과정 코드 뽑아냄 
    SELECT OPC_CODE INTO V_OPC_CODE
    FROM TBL_SUGANG
    WHERE SG_CODE = V_SG_CODE;
    
    -- 연결
    --SELECT OPC_CODE INTO CV_OPC_CODE
    --FROM TBL_OP_COURSE
    --WHERE OPC_CODE = V_OPC_CODE;
    
    -- 배점 코드 뽑아냄 
    SELECT AL_CODE INTO V_AL_CODE
    FROM TBL_OP_SUBJECT
    WHERE OPC_CODE = CV_OPC_CODE;
    
    -- 위의 배점 코드를 이용하여 배점 테이블에서 각 배점들 뽑아냄 
    SELECT A_ALLOT, W_ALLOT, P_ALLOT INTO V_A_ALLOT, V_W_ALLOT, V_P_ALLOT
    FROM TBL_ALLOT
    WHERE AL_CODE = V_AL_CODE;

    IF ( V_A_SCORE > V_A_ALLOT OR V_W_SCORE > V_W_ALLOT OR V_P_SCORE > V_P_ALLOT )
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- 데이터 입력
    INSERT INTO TBL_SCORE(SC_CODE, SG_CODE, OPS_CODE, A_SCORE, W_SCORE, P_SCORE)
    VALUES(SEQ_SCORE.NEXTVAL, V_SG_CODE, V_OPS_CODE, V_A_SCORE, V_W_SCORE, V_P_SCORE);

    -- 커밋
    COMMIT;
    
    -- 예외처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20013, '배점을 잘못 입력하셨습니다.');
                ROLLBACK;
       WHEN OTHERS
            THEN ROLLBACK;
END;
--==>> Procedure PRC_SCORE_INSERT이(가) 컴파일되었습니다.

-- 성적 업데이트 프로시저 -- 
CREATE OR REPLACE PROCEDURE PRC_SCORE_UPDATE
( V_SC_CODE      IN TBL_SCORE.SC_CODE%TYPE
, V_A_SCORE      IN TBL_SCORE.A_SCORE%TYPE
, V_W_SCORE      IN TBL_SCORE.W_SCORE%TYPE
, V_P_SCORE      IN TBL_SCORE.P_SCORE%TYPE
)
IS
    V_OPS_CODE          TBL_OP_SUBJECT.OPS_CODE%TYPE;
    V_END_DATE          TBL_OP_SUBJECT.END_DATE%TYPE;
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    
    SELECT OPS_CODE INTO V_OPS_CODE
    FROM TBL_SCORE
    WHERE SC_CODE = V_SC_CODE;

    SELECT END_DATE INTO V_END_DATE
    FROM TBL_SCORE SC JOIN TBL_OP_SUBJECT SU
    ON SC.OPS_CODE = SU.OPS_CODE
    WHERE SC.SC_CODE = V_SC_CODE;
    
    
    IF(V_END_DATE > SYSDATE)
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    UPDATE TBL_SCORE
    SET A_SCORE =V_A_SCORE , W_SCORE =V_W_SCORE, P_SCORE =V_P_SCORE
    WHERE SC_CODE = V_SC_CODE; 
    
    COMMIT;
    
    
    EXCEPTION
    WHEN USER_DEFINE_ERROR
        THEN RAISE_APPLICATION_ERROR(-20008,'성적입력은 과목이 종료된 후에 가능합니다.');
             ROLLBACK;
    WHEN OTHERS THEN ROLLBACK;
    
END;
--==>>Procedure PRC_SCORE_UPDATE이(가) 컴파일되었습니다.

-- 성적 삭제
CREATE OR REPLACE PROCEDURE PRC_SCORE_DELETE
(V_CODE         IN TBL_SCORE.SC_CODE%TYPE
)
IS
BEGIN
    DELETE
    FROM TBL_SCORE
    WHERE SC_CODE = V_CODE;
    
   
    COMMIT; 
END;
--==>>Procedure PRC_SCORE_DELETE이(가) 컴파일되었습니다.






--------------------------------------------------------------------------------






--○ 교수 로그인 시 과목 출력 프로시저
CREATE OR REPLACE PROCEDURE PRC_PROFESSOR_PRINT
(V_ID IN TBL_PROFESSOR.P_ID%TYPE
)
IS
    V_P_NAME      TBL_PROFESSOR.P_NAME%TYPE;
    V_SJ_NAME      TBL_SUBJECT.SJ_NAME%TYPE;
    V_START_DATE    TBL_OP_SUBJECT.START_DATE%TYPE;
    V_END_DATE      TBL_OP_SUBJECT.END_DATE%TYPE;
    V_B_NAME     TBL_BOOK.B_NAME%TYPE;

    CURSOR CUR_PRO_ID_SELECT
    IS
        (SELECT 교수이름,과목이름,START_DATE "시작일",END_DATE"종료일",B_NAME"교재명"
        FROM  (SELECT*
                FROM  (SELECT 교수코드,  교수이름, 과목코드,과목이름  
                             FROM(SELECT 교수코드,교수이름,SJ_CODE
                                  FROM    (SELECT P_CODE "교수코드",P_NAME "교수이름"
                                        FROM TBL_PROFESSOR
                                        WHERE P_ID=V_ID)T
                                        JOIN
                                        (SELECT *
                                        FROM TBL_OP_SUBJECT)E
                                ON T.교수코드=E.P_CODE)K
                                JOIN
                                (SELECT SJ_CODE "과목코드", SJ_NAME "과목이름"
                                 FROM TBL_SUBJECT) L
                             ON  K.SJ_CODE=L.과목코드) O
                             JOIN
                             (SELECT*
                             FROM TBL_OP_SUBJECT)K
                ON O.과목코드=K.SJ_CODE)KK
                JOIN
                (SELECT*
                 FROM TBL_BOOK)KKK
        ON KK.B_CODE=KKK.B_CODE);
    
BEGIN

    OPEN CUR_PRO_ID_SELECT;
    LOOP
        FETCH CUR_PRO_ID_SELECT INTO  V_P_NAME, V_SJ_NAME,  V_START_DATE,  V_END_DATE,  V_B_NAME;
        EXIT WHEN CUR_PRO_ID_SELECT%NOTFOUND;
        --출력
        DBMS_OUTPUT.PUT_LINE(V_P_NAME||' , ' ||V_SJ_NAME||' , ' ||V_START_DATE||' , ' ||V_END_DATE||' , ' ||V_B_NAME);
    END LOOP;
    CLOSE CUR_PRO_ID_SELECT;
END;


-------------------------------VIEW---------------------------------------------


--○ 관리자 계정에서 등록된 학생 출력 (ADMIN_STUDENT_VIEW)
-- 출력 정보 : 학생 이름, 과정명, 수강과목, 수강과목 총점
CREATE OR REPLACE VIEW ADMIN_STUDENT_VIEW
AS
SELECT S.S_NAME "학생이름"
     , C.C_NAME "과정명"
     , SJ.SJ_NAME "수강과목"
     , (SC.A_SCORE + SC.P_SCORE + SC.W_SCORE) "수강과목 총점"
     , CASE WHEN D.D_CODE IS NOT NULL 
            THEN CONCAT('중도탈락 - ',TO_CHAR(D.D_CODE))
            ELSE NULL
       END "중도탈락여부"
FROM TBL_STUDENT S, TBL_SUGANG SG, TBL_COURSE C, TBL_OP_COURSE OPC, TBL_SUBJECT SJ, TBL_OP_SUBJECT OPS, TBL_SCORE SC, TBL_DROP D
WHERE S.S_CODE = SG.S_CODE(+)
  AND SG.OPC_CODE = OPC.OPC_CODE(+)
  AND OPC.OPC_CODE = OPS.OPC_CODE(+)
  AND OPS.OPS_CODE = SC.OPS_CODE(+)
  AND OPC.C_CODE = C.C_CODE(+)
  AND OPS.SJ_CODE = SJ.SJ_CODE(+)
  AND D.SG_CODE(+) = SG.SG_CODE
  AND SG.SG_CODE = SC.SG_CODE;
--==>> View ADMIN_STUDENT_VIEW이(가) 생성되었습니다.



--○ 학생 계정에서 과목 출력 (STUDENT_SUBJECT_VIEW)
-- 수강이 끝난 과목만 출력 가능
CREATE OR REPLACE VIEW STUDENT_SUBJECT_VIEW
AS
SELECT S.S_NAME "학생명", SJ.SJ_NAME "과목명"
FROM TBL_STUDENT S, TBL_SUGANG SG, TBL_OP_COURSE OPC, TBL_SUBJECT SJ, TBL_OP_SUBJECT OPS
WHERE S.S_CODE = SG.S_CODE(+)
  AND SG.OPC_CODE = OPC.OPC_CODE(+)
  AND OPS.OPC_CODE(+) = OPC.OPC_CODE
  AND OPS.SJ_CODE = SJ.SJ_CODE(+)
  AND OPS.END_DATE < SYSDATE;
--==>> View STUDENT_SUBJECT_VIEW이(가) 생성되었습니다.


--○ 관리자 계정에서 개설된 과정 출력 (ADMIN_OP_COURSE_VIEW)
-- 출력 정보: 과정명, 강의실, 과목명, 과목 기간, 교재 명, 교수자명

CREATE OR REPLACE VIEW ADMIN_OP_COURSE_VIEW
AS
SELECT C.C_NAME "과정명", R.R_NAME "강의실명", S.SJ_NAME "과목명"
     , OPS.START_DATE "과목시작일", OPS.END_DATE "과목종료일"
    , B.B_NAME "교재명", P.P_NAME "교수자명"
FROM TBL_COURSE C, TBL_ROOM R, TBL_SUBJECT S, TBL_OP_COURSE OPC, 
     TBL_OP_SUBJECT OPS, TBL_BOOK B, TBL_PROFESSOR P
WHERE P.P_CODE = OPS.P_CODE
  AND B.B_CODE = OPS.B_CODE
  AND S.SJ_CODE = OPS.SJ_CODE
  AND OPS.OPC_CODE = OPC.OPC_CODE
  AND OPC.C_CODE = C.C_CODE
  AND OPC.R_CODE = R.R_CODE;
--==>> View ADMIN_OP_COURSE_VIEW이(가) 생성되었습니다.



--○ 교수 계정에서 자신이 강의한 과목의 성적 출력 (SCORE_VIEW) ---미완성(중도탈락)
-- 출력 정보: 과목명, 과목 기간, 교재 명, 학생 명, 출결, 실기, 필기, 총점, 등수

--→ 중도 탈락된 학생이어도 이미 수강한 과목에 대해서는 정보 출력 가능해야 함 --> 지금으로썬 가능
--   + 그 사실을 화면에서 확인 가능해야 함 --> HOW?

-- (수강신청코드로 과목조회 → 
-- 학생이 들은 전체 과목 조회 가능 
-- → 중도 탈락 일자를 기준으로 미래의 과목들은 제외시킨다.)
  
CREATE OR REPLACE VIEW PROF_SCORE_VIEW
AS
SELECT SJ.SJ_NAME "과목명", OPS.START_DATE "과목시작일",OPS.END_DATE "과목종료일"
    , B.B_NAME "교재명", SD.S_NAME "학생명"
    , S.A_SCORE "출결점수", S.P_SCORE "실기점수", S.W_SCORE "필기점수"
    , (S.A_SCORE + S.P_SCORE + S.W_SCORE) "총점"
    , RANK()OVER(ORDER BY (S.A_SCORE + S.P_SCORE + S.W_SCORE) DESC) "등수"
    , P.P_NAME "교수명"
    , CASE WHEN D.D_CODE IS NOT NULL 
           THEN CONCAT('중도탈락 - ',TO_CHAR(D.D_CODE))
           ELSE NULL
       END "중도탈락여부"
FROM TBL_OP_SUBJECT OPS,TBL_SUBJECT SJ, TBL_SUGANG SG, TBL_STUDENT SD
    , TBL_OP_COURSE OPC, TBL_SCORE S, TBL_BOOK B, TBL_PROFESSOR P, TBL_DROP D
WHERE S.OPS_CODE = OPS.OPS_CODE(+)     -- SCORE, OP_SUBJECT
  AND OPS.OPC_CODE = OPC.OPC_CODE(+)   -- OP_COURSE, OP_SUBJECT
  AND OPC.OPC_CODE = SG.OPC_CODE(+)    -- SUGANG, OP_COURSE
  AND SG.S_CODE = SD.S_CODE(+)         -- SUGANG, STUDENT
  AND SG.SG_CODE = S.SG_CODE           -- SCORE, SUGANG
  AND OPS.SJ_CODE = SJ.SJ_CODE(+)      -- OP_SUBJECT, SUBJECT
  AND OPS.B_CODE = B.B_CODE(+)         -- OP_SUBJECT, BOOK
  AND OPS.P_CODE = P.P_CODE(+)         -- PROFESSOR, OP_SUBJECT
  AND SG.SG_CODE = D.SG_CODE(+);       -- DROP, SUGANG


--==>> View PROF_SCORE_VIEW이(가) 생성되었습니다.
  

--○ 교수 계정에서 담당과목 조회
CREATE OR REPLACE VIEW PROF_SUBJECT_VIEW
AS
SELECT SJ.SJ_NAME "과목명"
        , OPS.START_DATE "과목시작일"
        , OPS.END_DATE "과목종료일"
        , P.P_NAME "교수이름"
FROM TBL_OP_SUBJECT OPS,TBL_SUBJECT SJ, TBL_SUGANG SG
    , TBL_OP_COURSE OPC, TBL_PROFESSOR P
WHERE OPS.OPC_CODE = OPC.OPC_CODE   -- OP_COURSE, OP_SUBJECT
  AND SJ.SJ_CODE = OPS.SJ_CODE      -- OP_SUBJECT, SUBJECT
  AND OPC.OPC_CODE = SG.OPC_CODE    -- SUGANG, OP_COURSE
  AND OPS.START_DATE <=SYSDATE      -- 강의 예정인 과목 미출력
  AND SYSDATE < OPS.START_DATE+(OPS.END_DATE-OPS.START_DATE+10) -- 강의 종료후 10일 이내만 성적처리 가능하도록 과목출력
  AND OPS.P_CODE=P.P_CODE;          
   
SELECT 과목명, 과목시작일, 과목종료일
FROM PROF_SUBJECT_VIEW
WHERE 교수이름='김호진';

/*
JAVA	21/04/15	21/09/04
ORACLE	21/04/15	21/09/04
SPRING	21/04/01	21/04/12
*/


-- 관리자 계정에서 등록된 모든 과목 정보 출력 뷰
CREATE OR REPLACE VIEW ADMIN_SUBJECT_VIEW
AS
SELECT CO.C_NAME"과정명"
     , R.R_NAME"강의실"
     , SU.SJ_NAME"과목명"
     , OS.START_DATE"과목시작일"
     , OS.END_DATE"과목종료일"
     , BO.B_NAME"교재명"
     , PR.P_NAME"교수자명"
FROM TBL_COURSE CO, TBL_ROOM R, TBL_SUBJECT SU, TBL_OP_SUBJECT OS, TBL_BOOK BO, TBL_PROFESSOR PR, TBL_OP_COURSE OC
WHERE CO.C_CODE(+) = OC.C_CODE
  AND R.R_CODE(+) = OC.R_CODE 
  AND OC.OPC_CODE = OS.OPC_CODE(+)
  AND SU.SJ_CODE(+) = OS.SJ_CODE 
  AND BO.B_CODE(+) = OS.B_CODE 
  AND PR.P_CODE(+) = OS.P_CODE;
--==>> View ADMIN_SUBJECT_VIEW이(가) 생성되었습니다.

SELECT *
FROM ADMIN_SUBJECT_VIEW
ORDER BY 과목시작일;
--==>>
/*
과정명	            강의실	과목명	과목시작일	    과목종료일	    교재명	        교수자명
풀스택 SW개발자과정(G)	A강의실	JAVA	21/02/01	21/02/28	JAVA의 정석	    김호진
풀스택 SW개발자과정(G)	A강의실	ORACLE	21/03/01	21/03/31	ORACLE의 정석	    김호진
풀스택 SW개발자과정(G)	A강의실	HTML5	21/04/01	21/04/30	HTML5+CSS3의 정석	강창묵
풀스택 SW개발자과정(G)	A강의실	CSS3	21/05/01	21/05/31	HTML5+CSS3의 정석	강창묵
풀스택 SW개발자과정(G)	A강의실	SPRING	21/06/01	21/07/12	SPRING의 정석	    강창묵
빅데이터 개발자과정(B)	B강의실	JAVA	21/07/14	21/08/31	JAVA의 정석	    김동수
빅데이터 개발자과정(B)	B강의실	ORACLE	21/09/01	21/10/30	ORACLE의 정석	    김동수
빅데이터 개발자과정(B)	B강의실	PYTHON	21/11/01	21/11/30	PYTHON의 정석	    김태형
빅데이터 개발자과정(B)	B강의실	R	    21/12/01	21/12/21	R의 정석	        김태형
AI 융합 개발자과정(C)	F강의실					
*/


