SELECT *
FROM TAB;

DROP TABLE TBL_SCORE;

DROP TABLE TBL_DROP;

DROP TABLE TBL_SUGANG;

DROP TABLE TBL_OP_SUBJECT;

DROP TABLE TBL_OP_COURSE;

DROP TABLE TBL_SUBJECT;

DROP TABLE TBL_COURSE;

DROP TABLE TBL_ROOM;

DROP TABLE TBL_STUDENT;

DROP TABLE TBL_ALLOT;

DROP TABLE TBL_ADMIN;

DROP TABLE TBL_PROFESSOR;

SELECT * FROM USER_CONSTRAINTS;

SELECT *
FROM USER_SEQUENCES;

DROP SEQUENCE SEQ_ALLOT;
DROP SEQUENCE SEQ_DROP;
DROP SEQUENCE SEQ_OPS_CODE;
DROP SEQUENCE SEQ_OP_COURSE;
DROP SEQUENCE SEQ_SCORE;
DROP SEQUENCE SEQ_SUGANG;

-- 1. BIN$ 테이블 조회
SHOW RECYCLEBIN;
 
-- 2. BIN$ 테이블 삭제
PURGE RECYCLEBIN;
 
-- 3.만약 삭제된 테이블을 되살리고 싶을 때
-- FLASHBACK TABLE [테이블명] TO BEFORE DROP;
