SELECT USER
FROM DUAL;
--==>> HR

--○ TBL_DROP 테이블 생성
CREATE TABLE TBL_DROP
( D_CODE    NUMBER(4)
, SG_CODE   NUMBER(4)   NOT NULL 
, REASON    VARCHAR2
, DR_DATE   DATE        DEFAULT SYSDATE
, CONSTRAINT DROP_D_CODE_PK PRIMARY KEY(D_CODE)
, CONSTRAINT DROP_SG_CODE_FK FOREIGN KEY(SG_CODE)
             REFERENCES TBL_SUGANG(SG_CODE)
);



