SELECT USER
FROM DUAL;
--==>> HR

--○ TBL_SCORE 테이블 생성
CREATE TABLE TBL_SCORE
( SC_CODE   NUMBER(4)
, SG_CODE   NUMBER(4)   NOT NULL
, OPS_CODE  NUMBER(4)   NOT NULL
, A_SCORE   NUMBER(3)
, W_SCORE   NUMBER(3)
, P_SCORE   NUMBER(3)
, CONSTRAINT SCORE_SC_CODE_PK PRIMARY KEY(SC_CODE)
, CONSTRAINT SCORE_SG_CODE_FK FOREIGN KEY(SG_CODE)
             REFERENCES TBL_SUGANG(SG_CODE)
, CONSTRAINT SCORE_OPS_CODE_FK FOREIGN KEY(OPS_CODE)
             REFERENCES TBL_OP_SUBJECT(OPS_CODE)
);